#!/bin/bash

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d I II III IV V VI VII VIII IX X
bspc monitor DP-3 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config borderless_monocle on
bspc config gapless_monocle on
bspc config split_ratio 0.500000
bspc config window_gap 5

bspc rule -r '*'


# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating


~/.dotfiles/bin/xrandr.sh &
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x polybar >/dev/null || MONITOR=DP-3 polybar bar &
pgrep -x dunst >/dev/null || dunst &
pgrep -x picom >/dev/null || picom &
steam &
discord &
