[[language]]
name = "javascript"
auto-format = true
formatter = { command = "bunx", args = ["prettier", "--parser", "javascript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "bunx", args = ["prettier", "--parser", "typescript"] }
