#!/bin/sh

xrandr \
  --output HDMI-0 --mode 1920x1080 --rate 60 --pos 4480x360 \
  --output DP-0 --mode 2560x1440 --rate 180 --pos 1920x0 --primary \
  --output DP-3 --mode 1920x1080 --rate 60 --pos 0x360

monitors=$(xrandr --listmonitors | awk '/\+/ {print $3, $4}' | cut -d'+' -f2- | sort -n | awk '{print $2}')
for monitor in $monitors; do
  bspc monitor $monitor -d I II III IV V VI VII VIII IX X
done
polybar_monitor=$(echo $monitors | awk '{print $1}')

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# auto start
pgrep -x sxhkd >/dev/null || sxhkd &
/usr/lib/polkit-kde-authentication-agent-1 &
XDG_MENU_PREFIX=arch- kbuildsycoca6 --noincremental
killall -q polybar
MONITOR=$polybar_monitor polybar bar &
dunst &
discord &
steam &
